#!/usr/bin/env python
#
# Podman Presto - quick containers in the shell that work how I want it
#
# XXX Clean all the testing containers with
# podman ps |grep pp-baseimage | awk '{print $1}' | xargs -- podman stop

import argparse
import json
import os
import random
import re
import string
import subprocess
import tempfile

_IMAGE_NAME = "pp-baseimage:latest"


class PodmanError(RuntimeError):
    pass


class Podman:

    def run(self, container_spec):
        ret = subprocess.run(["podman", "run", "-d", "--rm", "--network", "host", "--systemd=true",
                              "-v", container_spec.volume, "--name", container_spec.name, "--hostname",
                              container_spec.hostname,
                              "--label", container_spec.label, container_spec.image], capture_output=True, text=True)
        if ret.returncode != 0:
            raise PodmanError(ret.stderr)
        # ContainerID
        return ret.stdout.strip()

    def stop(self, id):
        ret = subprocess.run(["podman", "stop", id], capture_output=True, text=True)
        ret.check_returncode()
        return ret.stdout.strip()

    # Intentionally exec's and replaces this process
    def exec(self, id):
        os.execvp("podman", ["podman", "exec", "-t", "-i", "-w", "/pp", id, "bash"])

    def list(self):
        # podman ps -a --filter "label=net.ryandoyle.pp.pwd" --format json
        ret = subprocess.run(["podman", "ps", "-a", "--filter", "label=net.ryandoyle.pp.pwd", "--format", "json"],
                             capture_output=True, text=True)
        if ret.returncode != 0:
            raise PodmanError(ret.stderr)


        return json.loads(ret.stdout)

    def build(self, build_spec):
        ret = subprocess.run(["podman", "build", "--no-cache", "-f", build_spec.dockerfile_path,
                            "-t", build_spec.tag, build_spec.context_dir]) 
        if ret.returncode != 0:
            raise PodmanError(ret.stderr)


class BuildSpec:

    def __init__(self, context_dir):
        self.context_dir = context_dir

    @property
    def tag(self):
        return _IMAGE_NAME

    @property
    def dockerfile_path(self):
        f = open(f"{self.context_dir}/Dockerfile", "w")
        f.write(self.dockerfile)
        return f"{self.context_dir}/Dockerfile"

    @property
    def dockerfile(self):
        return """
FROM ubuntu:22.04

RUN apt-get update ; \
    apt-get install -y systemd systemd-sysv ; \
    apt-get install -y vim silversearcher-ag ; \
    apt-get clean ; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* ; \
    cd /lib/systemd/system/sysinit.target.wants/ ; \
    ls | grep -v systemd-tmpfiles-setup | xargs rm -f $1 ; \
    rm -f /lib/systemd/system/multi-user.target.wants/* ; \
    rm -f /etc/systemd/system/*.wants/* ; \
    rm -f /lib/systemd/system/local-fs.target.wants/* ; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev* ; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl* ; \
    rm -f /lib/systemd/system/basic.target.wants/* ; \
    rm -f /lib/systemd/system/anaconda.target.wants/* ; \
    rm -f /lib/systemd/system/plymouth* ; \
    rm -f /lib/systemd/system/systemd-update-utmp*

VOLUME [ "/sys/fs/cgroup" ]

CMD ["/lib/systemd/systemd"]
"""


class ContainerSpec:

    def __init__(self):
        self.random_part = ''.join(random.choices(string.ascii_lowercase, k=8))

    @property
    def label(self):
        return f"net.ryandoyle.pp.pwd={os.getcwd()}"

    @property
    def volume(self):
        return f"{os.getcwd()}:/pp"

    @property
    def name(self):
        return f"pp-{self.random_part}"

    @property
    def hostname(self):
        return f"pp-{self.random_part}-{re.sub('[^0-9a-zA-Z]+', '-', os.getcwd())[-80:]}"

    @property
    def image(self):
        return _IMAGE_NAME


class PPContainerDto:

    def __init__(self, json_obj) -> None:
        self.json_obj = json_obj

    @property
    def id(self):
        return self.json_obj["Id"][:12]

    @property
    def path(self):
        return self.json_obj["Labels"]["net.ryandoyle.pp.pwd"]

    @property
    def status(self):
        return self.json_obj["Status"]


class PPContainerViewDto:
    def __init__(self, pp_container_dto):
        self.pp_container_dto = pp_container_dto

    def as_array_fmt(self):
        return [self.pp_container_dto.id, self.path_highlighting_cwd, self.pp_container_dto.status]

    @property
    def path_highlighting_cwd(self):
        if os.getcwd() == self.pp_container_dto.path:
            return f"{self.pp_container_dto.path} (*)"
        return self.pp_container_dto.path


class PPService:
    def __init__(self) -> None:
        self.podman = Podman()

    def create_pp(self):
        c = ContainerSpec()
        id = self.podman.run(c)
        return id

    def enter_pp(self, id):
        self.podman.exec(id)

    def purge_pp(self, id):
        self.podman.stop(id)

    def find_pp_for_cwd(self):
        return list(filter(lambda c: c.path == os.getcwd(), self.list_pp()))

    def list_pp(self):
        return list(map(lambda p: PPContainerDto(p), self.podman.list()))

    def build_base_image(self):
        with tempfile.TemporaryDirectory(prefix="pp-dockerfile-builder") as d_name:
            spec = BuildSpec(d_name)
            self.podman.build(spec)


class PPListCommand:
    def __init__(self, pp_service):
        self.pp_service = pp_service

    def run(self):
        formatter = "{:<12}  {:<50}  {:<40}".format
        print(formatter("ID", "PATH", "STATUS"))
        for p in self.pp_service.list_pp():
            print(formatter(*PPContainerViewDto(p).as_array_fmt()))


class PPEnterCommand:
    def __init__(self, pp_service):
        self.pp_service = pp_service

    def run(self):
        pps = self.pp_service.find_pp_for_cwd()
        if len(pps) == 0:
            print("Creating new container for this path...")
            id = self.pp_service.create_pp()
            self.pp_service.enter_pp(id)
        elif len(pps) == 1:
            self.pp_service.enter_pp(pps[0].id)
        else:
            print(f"Warning: more than 1 container at this path. Entering oldest ({pps[0].id})...")
            self.pp_service.enter_pp(pps[0].id)


class PPPurgeCommand:
    def __init__(self, pp_service):
        self.pp_service = pp_service

    def run(self):
        pps = self.pp_service.find_pp_for_cwd()
        if len(pps) == 0:
            print(f"Warning: No container at {os.getcwd()} to purge")
        elif len(pps) > 1:
            print(f"Warning: More than 1 container at {os.getcwd()}. Specify container id")
        else:
            self.pp_service.purge_pp(pps[0].id)


class PPBuildCommand:
    def __init__(self, pp_service) -> None:
        self.pp_service = pp_service

    def run(self):
        self.pp_service.build_base_image()


def main():
    parser = argparse.ArgumentParser(description="Quick containers in your shell")
    parser.add_argument('-l', '--list', action="store_true", help='List containers')
    parser.add_argument('-p', '--purge', action="store_true", help='Purge containers')
    parser.add_argument('-b', '--build', action="store_true", help='Build base image')
    args = parser.parse_args()

    pp = PPService()

    if args.list:
        PPListCommand(pp).run()
    elif args.purge:
        PPPurgeCommand(pp).run()
    elif args.build:
        PPBuildCommand(pp).run()
    else:
        PPEnterCommand(pp).run()


if __name__ == '__main__':
    main()
